INSERT INTO DEPARTMENT(PK_DEPARTMENT_ID, NAME) VALUES (1, 'finance');
INSERT INTO DEPARTMENT(PK_DEPARTMENT_ID, NAME) VALUES (2, 'it');


INSERT INTO USER (PK_USER_ID ,FIRST_NAME ,LAST_NAME ,FK_DEPARTMENT_ID ) VALUES(1, 'John', 'Doe', 1);
INSERT INTO USER (PK_USER_ID ,FIRST_NAME ,LAST_NAME ,FK_DEPARTMENT_ID ) VALUES(2, 'Peter', 'Johnson', 2);


INSERT INTO TASK (PK_TASK_ID, CREATED, DESCRIPTION, STATUS, THEME, AUTHOR, EXECUTOR ) VALUES(1, NOW(), 'Do it best', 'IN_PROGRESS', 'Do something', 1, 1);
INSERT INTO TASK (PK_TASK_ID, CREATED, DESCRIPTION, STATUS, THEME, AUTHOR, EXECUTOR ) VALUES(2, NOW(), 'Do it best', 'READY_FOR_QA', 'Do something', 1, 2);

INSERT INTO COMMENT(PK_COMMENT_ID, CONTENT, CREATED, FK_TASK_ID, FK_AUTHOR_ID) VALUES(1, 'Please clarify requirements', NOW(), 1, 1);
INSERT INTO COMMENT(PK_COMMENT_ID, CONTENT, CREATED, FK_TASK_ID, FK_AUTHOR_ID) VALUES(2, 'Need more info', NOW(), 2, 1);
INSERT INTO COMMENT(PK_COMMENT_ID, CONTENT, CREATED, FK_TASK_ID, FK_AUTHOR_ID) VALUES(3, 'You can test this on stage server', NOW(), 2, 1);
