INSERT INTO DEPARTMENT(PK_DEPARTMENT_ID, NAME) VALUES (1, 'finance');
INSERT INTO DEPARTMENT(PK_DEPARTMENT_ID, NAME) VALUES (2, 'it');


INSERT INTO USER (FIRST_NAME ,LAST_NAME ,FK_DEPARTMENT_ID ) VALUES('John', 'Doe', 1);
INSERT INTO USER (FIRST_NAME ,LAST_NAME ,FK_DEPARTMENT_ID ) VALUES('Peter', 'Johnson', 2);


INSERT INTO TASK (CREATED, DESCRIPTION, STATUS, THEME, AUTHOR, EXECUTOR ) VALUES(NOW(), 'Do it best', 'IN_PROGRESS', 'Do something', 1, 1);
INSERT INTO TASK (CREATED, DESCRIPTION, STATUS, THEME, AUTHOR, EXECUTOR ) VALUES(NOW(), 'Do it best', 'READY_FOR_QA', 'Do something', 1, 2);

INSERT INTO COMMENT(CONTENT, CREATED, FK_TASK_ID, FK_AUTHOR_ID) VALUES('Please clarify requirements', NOW(), 1, 1);
INSERT INTO COMMENT(CONTENT, CREATED, FK_TASK_ID, FK_AUTHOR_ID) VALUES('Need more info', NOW(), 2, 1);
